version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - SENDGRID_API_KEY=your_api_key

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true